### ISSUE TITLE
Database Configuration Error with Heroku @climateamante

### ISSUE THREAD

**Issue by Rapdash** [climateamante/remote.team.onboarding.project.management#22]
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

Running into this error when deploying to Heroku using their recommended method. Been blocked on it for ~1 hour.

Steps to reproduce:

1.  Generate Django App
2. Install  & import dj-database-url && psycopg2 (version 2.7)
3.
```
# set 
DATABASES['default'] == to dj_database_url.config in Settings.py
```
BELOW everything else as per docs
4. Deploy to heroku dyno that already has a DB string configured in env vars

@climateamante ^^

**Comment by climateamante** [comment]
@Rapdash - when I have a chance to deep dive into this error and edge-case I will add it to the documentation. thank you for flagging the issue.
