### ISSUE TITLE
@maria - branch.workflow and cleanup

### ISSUE THREAD

**Issue by climateamante** [climateamante/remote.team.onboarding.project.management#26]
branch structure:
 - master (everything needed for local)
	- include links to production (front & back)

 - debug.django
 - debug.react
 - staging.backend
 - staging.frontend
 - production.backend
 - production.frontend

**Comment by climateamante** [comment]
@geekwise-maria-navarro - Feel free to close this issue.

![Screen Shot 2019-12-27 at 3 07 43 PM 1](https://user-images.githubusercontent.com/29623356/71535429-e937d580-28ba-11ea-9db5-3ec0499b4a82.png)

**Comment by geekwise-maria-navarro** [comment]
Got it! Thanks!
