### ISSUE TITLE
@maria - debug model `boolean` error for heroku branch: `staging.backend`

### ISSUE THREAD

**Issue by climateamante** [climateamante/remote.team.onboarding.project.management#27]
[Reference to Django docs on model, options, boolean](https://docs.djangoproject.com/en/2.2/ref/models/fields)

**Comment by geekwise-maria-navarro** [comment]
Thanks Climate for your help!

**Comment by geekwise-maria-navarro** [comment]
Thanks Climate for your help!

**Comment by geekwise-maria-navarro** [comment]
Thanks @climateamante for your help!
