### ISSUE TITLE
Cross origin read block

### ISSUE THREAD

**Issue by geekwise-ashkan-nadiri** [climateamante/remote.team.onboarding.project.management#28]
I am currently getting this [error](https://github.com/geekwise-ashkan-nadiri/django.drf.react.bank.project/issues/2) while getting data from heroku url.

**Comment by Rapdash** [comment]
Hey @geekwise-ashkan-nadiri ; My first thought after visiting the "branches" page on your frontend is that you've got some configuration I wouldn't expect on the post requests. In regards to your specific question, though, it seems you've figured it out. If that's correct, would you mind closing the issue?

**Comment by climateamante** [comment]
@geekwise-ashkan-nadiri  - is this issue still a hard block?
