### ISSUE TITLE
[@Jesus | project board](https://github.com/geekwise-Jesus-Garcia/django.drf.react.bank.project)

### ISSUE THREAD

**Issue by geekwise-Jesus-Garcia** [climateamante/remote.team.onboarding.project.management#29]
! some one deleted mycard

**Comment by Rapdash** [comment]
@geekwise-Jesus-Garcia Does this issue need to remain open? I think the cards are deleted for people when they take a day off (mine was) but I might be mistaken. If you've got this handled, mind closing the issue?
