### ISSUE TITLE
@fritz: soft block - no markdown in the master branch for heroku review

### ISSUE THREAD

**Issue by climateamante** [climateamante/remote.team.onboarding.project.management#33]

**Comment by climateamante** [comment]
![Screen Shot 2019-12-31 at 1 18 15 PM 1](https://user-images.githubusercontent.com/29623356/71634354-25777880-2bd0-11ea-9ece-ddd6ee0874d3.png)

**Comment by Rapdash** [comment]
Done to a functional  standard.
